server:
  port: 8080

spring:
  datasource:
    username: root
    password: root1234
    url: jdbc:mysql://localhost:3306/metadb
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none #create update none
    properties:
      hibernate:
        default_batch_fetch_size: 100
        #show-sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
